mysite2/mysite2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('portal/', include('portal.urls', namespace='portal')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', views.main_page),
    path('', include('django.contrib.auth.urls')),
    path('logout/', views.logout_view, name='logout_view'),

]

mysite2/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

mysite2/portal/urls.py
#controller dell'applicazione portal

from django.urls import path
from . import views

app_name = 'portal'

urlpatterns = [
    #ex /portal/
    path('', views.portal_welcome, name='portal_welcome'),
    path('contact/', views.contact, name='contact'),
    path('thanks/', views.thanks, name='thanks'),
    path('upload/', views.upload, name='upload')
]

mysite2/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    #permessi aggiuntivi oltre ai default: add, delete and change
    class Meta:
        permissions = (('can_vote','Can Vote Polls'), )

    def was_published_recently(self):
        # timedelta serve in questo caso per togliere un giorno dal tempo attuale
        now = timezone.now()
        value = now - datetime.timedelta(days=1) <= self.pub_date <= now
        return value

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite2/portal/models.py
from django.db import models

# Create your models here.

mysite2/portal/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

mysite2/mysite2/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.http import HttpResponseRedirect

def main_page(request):
    return render(request, 'index.html')

def logout_view(request):
    logout(request)
    return render(request, 'index.html')

mysite2/polls/views.py
from django.http import HttpResponse
from .models import Question
from django.template import loader
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone

def index(request):
    latest_qlist = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_qlist
    }

    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk= question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk= question_id)
    return render(request, 'polls/render.html', {'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk= request.POST['choice'])
    except:
        return render(request, 'polls/detail.html', {'question': p, 'error_message': "you didin't select a choiche"})
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite2/portal/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from portal.forms import *
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponse
from .forms import UploadFileForm

@login_required
def portal_welcome(request):
    return render(request, 'portal/index.html', {'request': request})

def contact(request):
    #if the formhas been submitted

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']
            recipients = ['erry.robby@gmail.com']
            if cc_myself:
                recipients.append(sender)
            #send_mail(subject, message, sender, recipients)
            print('email mandata: ', subject, sender, recipients)
            #redirect after post

            return HttpResponseRedirect('/portal/thanks')

    else:
        #just visualize the form
        form = ContactForm()
        return render(request, 'portal/contact.html', {'form': form})

def thanks(request):
    return render(request, 'portal/thanks.html')

def upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            #handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/portal/thanks')
    else:
        form = UploadFileForm()
        return render(request, 'uploadForm.html', {'form': form})

mysite2/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choiche {{ foorloop.counter }}" value="{{ choice.id }}"/>
        <label>{{ choice.choice_text }}</label>
        <br>
        {% endfor %}
        <br>
        <input type="submit" value="Vote">
</form>

mysite2/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="/polls/{{ question.id }}/">
                    {{ question.question_text }}

                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite2/polls/templates/polls/render.html
<h1> {{ question.question_text }}</h1>
{% for choice in question.choice_set.all %}
<label>
    {{ choice.choice_text }} : {{ choice.votes }} vote{{ choice.votes | pluralize }}
</label><br>
{% endfor %}
<a href="{% url 'polls:detail' question.id %}">vote again? </a>

mysite2/portal/templates/portal/contact.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

mysite2/portal/templates/portal/index.html
{% extends "portal/portal.html" %}
{% comment %} wlecome page portal {% endcomment %}
{% block title %} Welcome page {% endblock %}
{% block content %}
<section>
    <h2>Welcome {{ request.user.username | capfirst }}</h2>
    <p>this is the entry page of the portal </p>
</section>
{% endblock %}

mysite2/portal/templates/portal/portal.html
{% extends "base.html" %}
{% comment %}
This is the main template for all portal pages.
{% endcomment %}
{% block head %}
<title>Web Portal | {% block title %}{% endblock %}</title>
{% endblock %}
{% block body %}
<header>
<h1> Django Mysite | Web Portal</h1>
</header>
<section>
    <ul>
        <li>
            <a href="/">Main page</a>
        </li>
        <li>
            <a href="{% url 'polls:index' %}"> Polls app</a>
        </li>
        <li><a href="{% url 'portal:contact' %}">Contact</a> </li>
        <li><a href="{% url 'portal:upload' %}">Upload files form</a></li>
        <li><a href="{% url 'logout_view' %}">Logout</a></li>

    </ul>
</section>
{% block content %}{% endblock %}
<footer>
    <span>&copy; 2019, Django</span>
</footer>
{% endblock %}

mysite2/portal/templates/portal/thanks.html
<h2>Operation completed with success</h2>
<p>click <a href="{% url 'portal:portal_welcome' %}">here</a> to return to the home page </p>

mysite2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    {% block head %} {% endblock %}
    <link rel="stylesheet" type="text/css"  href="{% static 'polls/style.css' %}" />

</head>
<body>
{% block body %} {% endblock %}
</body>
</html>

mysite2/templates/index.html
{% extends "base.html" %}
{% comment %} Main page of django_mysite.
{% endcomment %}
{% block head %}
<title> Django mysite </title>
{% endblock %}
{% block body %}
<header>
    <h1>Django mysite</h1>
    <section>
        <p>welcome to django mysite, click
        <a href="{% url 'portal:portal_welcome' %}">here</a>
            to log in our web portal
        </p>
    </section>
</header>
{% endblock %}

mysite2/templates/uploadForm.html
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>